# Generated by Django 5.2.15 on 2026-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
