# Generated by Django 5.2.15 on 2026-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_exam_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('spec_L', models.BooleanField(default=False, verbose_name='L – lekarz systemu')),
                ('spec_P', models.BooleanField(default=False, verbose_name='P – pielęgniarka systemu')),
                ('spec_Ps', models.BooleanField(default=False, verbose_name='Ps – psycholog')),
                ('spec_R', models.BooleanField(default=False, verbose_name='R – ratownik')),
                ('spec_Rt', models.BooleanField(default=False, verbose_name='Rt – ratownictwo techniczne')),
                ('spec_Rch', models.BooleanField(default=False, verbose_name='Rch – ratownictwo chemiczne')),
                ('spec_Re', models.BooleanField(default=False, verbose_name='Re – ratownictwo ekologiczne')),
                ('spec_Rwo', models.BooleanField(default=False, verbose_name='Rwo – ratownictwo wodne')),
                ('spec_Rwy', models.BooleanField(default=False, verbose_name='Rwy – ratownictwo wysokościowe')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.instructor'),
        ),
    ]
