# Generated by Django 5.2.15 on 2026-07-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_instructor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Staż pracy (lata)'),
        ),
    ]
