# Generated by Django 5.2.15 on 2026-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_instructor_years_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='years_experience',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Staż pracy'),
        ),
    ]
