# Generated by Django 5.2.15 on 2026-08-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_change_years_experience_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course'),
        ),
    ]
