# Generated by Django 5.2.15 on 2026-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment_deposit_paid_alter_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deletion_reason',
            field=models.CharField(blank=True, choices=[('forfeit', 'Rezygnacja (bez powodu) – zaliczka przepadła'), ('refund', 'Rezygnacja z przyczyn losowych – zwrot zaliczki'), ('reschedule', 'Rezygnacja z przyczyn losowych – zmiana terminu')], max_length=15),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
