# Generated by Django 5.2.15 on 2026-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_enrollment_course_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
