# Generated by Django 5.2.15 on 2026-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_birth_date_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_order',
            field=models.JSONField(default=list),
        ),
    ]
