# Generated by Django 5.2.15 on 2026-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_instructor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
