# Generated by Django 5.2.15 on 2026-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
