# Generated by Django 5.2.15 on 2026-08-18 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_whatsapp_link_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
