# Generated by Django 5.2.15 on 2026-08-27 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_fix_double_encrypted_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
