# Generated by Django 5.2.15 on 2026-08-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_fix_created_at_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cert_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
