# Generated by Django 5.2.17 on 2026-09-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_enrollment_exam_theory_committee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='visibility_auto_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
