# Generated by Django 5.2.17 on 2026-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_instructor_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='exam_chair_rko',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_chair_zad1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_chair_zad2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_member1_rko',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_member1_zad1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_member1_zad2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_member2_rko',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_member2_zad1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_member2_zad2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
