# Generated by Django 5.2.15 on 2026-09-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_topicfileprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
